'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USER
    Public Property UserId As Integer
    Public Property Username As String
    Public Property Password As String
    Public Property Email As String
    Public Property CreatedDate As Date
    Public Property LastLoginDate As Nullable(Of Date)
    Public Property FirstName As String
    Public Property LastName As String
    Public Property TelephoneNumber As String

End Class
Partial Public Class USERACTIVATION
    Public Property UserId As Integer
    Public Property ActivationCode As System.Guid

End Class
