'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class BuckheadBusDatabaseEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BuckheadBusDatabaseEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property USERS() As DbSet(Of USER)
    Public Overridable Property USERACTIVATIONs() As DbSet(Of USERACTIVATION)

    Public Overridable Function Insert_User(username As String, password As String, email As String, firstName As String, lastName As String, telephoneNumber As String) As ObjectResult(Of Nullable(Of Integer))
        Dim usernameParameter As ObjectParameter = If(username IsNot Nothing, New ObjectParameter("Username", username), New ObjectParameter("Username", GetType(String)))

        Dim passwordParameter As ObjectParameter = If(password IsNot Nothing, New ObjectParameter("Password", password), New ObjectParameter("Password", GetType(String)))

        Dim emailParameter As ObjectParameter = If(email IsNot Nothing, New ObjectParameter("Email", email), New ObjectParameter("Email", GetType(String)))

        Dim firstNameParameter As ObjectParameter = If(firstName IsNot Nothing, New ObjectParameter("FirstName", firstName), New ObjectParameter("FirstName", GetType(String)))

        Dim lastNameParameter As ObjectParameter = If(lastName IsNot Nothing, New ObjectParameter("LastName", lastName), New ObjectParameter("LastName", GetType(String)))

        Dim telephoneNumberParameter As ObjectParameter = If(telephoneNumber IsNot Nothing, New ObjectParameter("TelephoneNumber", telephoneNumber), New ObjectParameter("TelephoneNumber", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Nullable(Of Integer))("Insert_User", usernameParameter, passwordParameter, emailParameter, firstNameParameter, lastNameParameter, telephoneNumberParameter)
    End Function

End Class
